apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: template-renderer
rules:
- apiGroups: ["*"]
  resources: ["secrets", "configmaps", "events"]
  verbs: ["*"]
- apiGroups: ["exphost.pl"]
  resources: ["templates"]
  verbs: ["get", "list", "watch", "patch"]
